/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type LegalDoc = {
  _id: string;
  _type: "legalDoc";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  label?: string;
  eyebrow?: string;
  entity?: string;
  updatedAt: string;
  intro: string;
  sections: Array<
    {
      _key: string;
    } & LegalSection
  >;
  order?: number;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: Figure;
  noIndex?: boolean;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type FaqGroup = {
  _id: string;
  _type: "faqGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  navLabel: string;
  items: Array<
    {
      _key: string;
    } & FaqItem
  >;
  order?: number;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  dek: string;
  heroImage?: Figure;
  body?: PostBody;
  category: CategoryReference;
  author: PersonReference;
  publishedAt: string;
  readTime?: number;
  featured?: boolean;
  related?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: Seo;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role: string;
  initials?: string;
  photo?: Figure;
  bio?: string;
  funFact?: {
    label?: string;
    text?: string;
  };
  onTeamPage?: boolean;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  order?: number;
};

export type PostBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Figure)
  | {
      text: string;
      attribution?: string;
      _type: "pullQuote";
      _key: string;
    }
  | {
      text: string;
      _type: "callout";
      _key: string;
    }
>;

export type NewsletterPage = {
  _id: string;
  _type: "newsletterPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  formTitle?: string;
  formButtonLabel?: string;
  formDisclaimer?: string;
  formSuccessSticker?: string;
  formSuccessText?: string;
  whyHeader?: SectionHeader;
  whyReasons?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  insideHeader?: SectionHeader;
  insideItems?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  afterHoursHeader?: SectionHeader;
  afterHoursBody?: RichText;
  ctaEyebrow?: string;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButton?: Link;
  ctaSecondaryLabel?: string;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
  openInNewTab?: boolean;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Headline = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SectionHeader = {
  _type: "sectionHeader";
  eyebrow?: string;
  headline?: Headline;
  sticker?: string;
  intro?: RichText;
};

export type PageHero = {
  _type: "pageHero";
  badge?: string;
  headline: Headline;
  intro?: RichText;
  cta?: Link;
  sticker?: string;
};

export type FreeAuditPage = {
  _id: string;
  _type: "freeAuditPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  navCtaLabel?: string;
  coverHeader?: SectionHeader;
  coverCards?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  forYouHeader?: SectionHeader;
  forYouPointers?: Array<string>;
  deliverablesHeader?: SectionHeader;
  deliverables?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  faqHeader?: SectionHeader;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  proofHeader?: SectionHeader;
  proofSticker?: string;
  proofBody?: string;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButton?: Link;
  seo?: Seo;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButtons?: Cta;
  seo?: Seo;
};

export type Cta = {
  _type: "cta";
  primary?: Link;
  secondary?: Link;
};

export type BlogIndexPage = {
  _id: string;
  _type: "blogIndexPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  topReadsHeader?: SectionHeader;
  archiveHeader?: SectionHeader;
  newsletterHeadline?: Headline;
  newsletterBody?: RichText;
  newsletterCta?: Link;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButtons?: Cta;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: PageHero;
  whatWeAreEyebrow?: string;
  whatWeAreBody?: RichText;
  missionEyebrow?: string;
  missionStatement?: string;
  storyEyebrow?: string;
  storyHeadline?: Headline;
  storyBeats?: Array<string>;
  teamEyebrow?: string;
  teamHeadline?: string;
  teamSticker?: string;
  teamIntro?: RichText;
  ctaEyebrow?: string;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButtons?: Cta;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroBadge?: string;
  heroHeadline: Headline;
  heroIntro?: RichText;
  heroCta?: Cta;
  heroFootnote?: string;
  heroStickerA?: string;
  heroStickerB?: string;
  problemHeader?: SectionHeader;
  problemBody?: RichText;
  lookalikes?: Array<string>;
  problemSticker?: string;
  problemCaption?: string;
  funnelHeader?: SectionHeader;
  funnelStages?: Array<
    {
      _key: string;
    } & FunnelStage
  >;
  funnelOutcomeSticker?: string;
  funnelOutcomeText?: string;
  whyHeader?: SectionHeader;
  whyReasons?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  howHeader?: SectionHeader;
  howPhases?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  howBanner?: string;
  whoHeader?: SectionHeader;
  whoSegments?: Array<
    {
      _key: string;
    } & TitledCard
  >;
  proofHeader?: SectionHeader;
  proofBody?: RichText;
  proofCta?: Link;
  proofSticker?: string;
  auditHeader?: SectionHeader;
  auditBody?: RichText;
  auditCta?: Link;
  auditSticker?: string;
  auditListTitle?: string;
  auditItems?: Array<string>;
  faqHeader?: SectionHeader;
  faqItems?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  ctaHeadline?: Headline;
  ctaBody?: RichText;
  ctaButtons?: Cta;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline?: string;
  contactEmail: string;
  marqueeText: string;
  headerNav?: Array<
    {
      _key: string;
    } & Link
  >;
  headerCta?: Link;
  footerGroups?: Array<{
    title: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _type: "footerGroup";
    _key: string;
  }>;
  footerNote?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  defaultSeo?: Seo;
};

export type LegalSection = {
  _type: "legalSection";
  title: string;
  blocks: Array<
    | ({
        _key: string;
      } & LegalParagraph)
    | ({
        _key: string;
      } & LegalClause)
    | ({
        _key: string;
      } & LegalSubheading)
    | ({
        _key: string;
      } & LegalDefinition)
    | ({
        _key: string;
      } & LegalList)
    | ({
        _key: string;
      } & LegalNote)
    | ({
        _key: string;
      } & LegalContact)
  >;
};

export type LegalContact = {
  _type: "legalContact";
  name: string;
  city?: string;
  email: string;
};

export type LegalNote = {
  _type: "legalNote";
  text: string;
};

export type LegalList = {
  _type: "legalList";
  items: Array<string>;
};

export type LegalDefinition = {
  _type: "legalDefinition";
  term: string;
  text: string;
};

export type LegalSubheading = {
  _type: "legalSubheading";
  number: string;
  heading: string;
};

export type LegalClause = {
  _type: "legalClause";
  number: string;
  heading: string;
  text: string;
};

export type LegalParagraph = {
  _type: "legalParagraph";
  text: string;
};

export type ServicePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "servicePage";
};

export type FunnelStage = {
  _type: "funnelStage";
  title: string;
  tag?: string;
  description: string;
  bullets?: Array<string>;
  barWidth: number;
  servicePage?: ServicePageReference;
};

export type ServicePage = {
  _id: string;
  _type: "servicePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category: string;
  slug: Slug;
  order?: number;
  heroHeadline: Headline;
  heroSub: string;
  problemHeadline: string;
  problemBody?: RichText;
  offerings: Array<
    {
      _key: string;
    } & TitledCard
  >;
  differently?: Array<string>;
  testimonial?: string;
  faq?: Array<
    {
      _key: string;
    } & FaqItem
  >;
  quoteHeadline: string;
  serviceScope?: string;
  serviceCheckboxes?: Array<string>;
  talkHeadline?: string;
  talkBody?: string;
  seo?: Seo;
};

export type TitledCard = {
  _type: "titledCard";
  title: string;
  description: string;
  tag?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: RichText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | LegalDoc
  | Seo
  | Slug
  | FaqGroup
  | CategoryReference
  | PersonReference
  | PostReference
  | Post
  | Person
  | SanityImageAssetReference
  | Figure
  | Category
  | PostBody
  | NewsletterPage
  | Link
  | RichText
  | Headline
  | SectionHeader
  | PageHero
  | FreeAuditPage
  | FaqPage
  | Cta
  | BlogIndexPage
  | AboutPage
  | HomePage
  | SiteSettings
  | LegalSection
  | LegalContact
  | LegalNote
  | LegalList
  | LegalDefinition
  | LegalSubheading
  | LegalClause
  | LegalParagraph
  | ServicePageReference
  | FunnelStage
  | ServicePage
  | TitledCard
  | FaqItem
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    tagline,    contactEmail,    marqueeText,    headerNav[] { label, href, openInNewTab },    headerCta { label, href, openInNewTab },    footerGroups[] {      title,      links[] { label, href, openInNewTab }    },    footerNote,    socialLinks[] { label, href, openInNewTab },    defaultSeo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string;
  tagline: string | null;
  contactEmail: string;
  marqueeText: string;
  headerNav: Array<{
    label: string;
    href: string;
    openInNewTab: boolean | null;
  }> | null;
  headerCta: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  footerGroups: Array<{
    title: string;
    links: Array<{
      label: string;
      href: string;
      openInNewTab: boolean | null;
    }> | null;
  }> | null;
  footerNote: string | null;
  socialLinks: Array<{
    label: string;
    href: string;
    openInNewTab: boolean | null;
  }> | null;
  defaultSeo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    heroBadge,    heroHeadline,    heroIntro,    heroCta { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },    heroFootnote,    heroStickerA,    heroStickerB,    problemHeader { eyebrow, headline, sticker, intro },    problemBody,    lookalikes,    problemSticker,    problemCaption,    funnelHeader { eyebrow, headline, sticker, intro },    funnelStages[] {      title,      tag,      description,      bullets,      barWidth,      "href": servicePage->slug.current    },    funnelOutcomeSticker,    funnelOutcomeText,    whyHeader { eyebrow, headline, sticker, intro },    whyReasons[] { title, description, tag },    howHeader { eyebrow, headline, sticker, intro },    howPhases[] { title, description, tag },    howBanner,    whoHeader { eyebrow, headline, sticker, intro },    whoSegments[] { title, description, tag },    proofHeader { eyebrow, headline, sticker, intro },    proofBody,    proofCta { label, href, openInNewTab },    proofSticker,    auditHeader { eyebrow, headline, sticker, intro },    auditBody,    auditCta { label, href, openInNewTab },    auditSticker,    auditListTitle,    auditItems,    faqHeader { eyebrow, headline, sticker, intro },    faqItems[] { question, answer },    ctaHeadline,    ctaBody,    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type HOME_PAGE_QUERY_RESULT = {
  heroBadge: string | null;
  heroHeadline: Headline;
  heroIntro: RichText | null;
  heroCta: {
    primary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    secondary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
  } | null;
  heroFootnote: string | null;
  heroStickerA: string | null;
  heroStickerB: string | null;
  problemHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  problemBody: RichText | null;
  lookalikes: Array<string> | null;
  problemSticker: string | null;
  problemCaption: string | null;
  funnelHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  funnelStages: Array<{
    title: string;
    tag: string | null;
    description: string;
    bullets: Array<string> | null;
    barWidth: number;
    href: string | null;
  }> | null;
  funnelOutcomeSticker: string | null;
  funnelOutcomeText: string | null;
  whyHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  whyReasons: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  howHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  howPhases: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  howBanner: string | null;
  whoHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  whoSegments: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  proofHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  proofBody: RichText | null;
  proofCta: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  proofSticker: string | null;
  auditHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  auditBody: RichText | null;
  auditCta: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  auditSticker: string | null;
  auditListTitle: string | null;
  auditItems: Array<string> | null;
  faqHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  faqItems: Array<{
    question: string;
    answer: RichText;
  }> | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButtons: {
    primary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    secondary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },    whatWeAreEyebrow,    whatWeAreBody,    missionEyebrow,    missionStatement,    storyEyebrow,    storyHeadline,    storyBeats,    teamEyebrow,    teamHeadline,    teamSticker,    teamIntro,    ctaEyebrow,    ctaHeadline,    ctaBody,    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} },    "team": *[_type == "person" && onTeamPage == true] | order(order asc, name asc) {  _id,  name,  role,  initials,  photo {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  bio,  funFact}  }
export type ABOUT_PAGE_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: Headline;
    intro: RichText | null;
    cta: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    sticker: string | null;
  } | null;
  whatWeAreEyebrow: string | null;
  whatWeAreBody: RichText | null;
  missionEyebrow: string | null;
  missionStatement: string | null;
  storyEyebrow: string | null;
  storyHeadline: Headline | null;
  storyBeats: Array<string> | null;
  teamEyebrow: string | null;
  teamHeadline: string | null;
  teamSticker: string | null;
  teamIntro: RichText | null;
  ctaEyebrow: string | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButtons: {
    primary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    secondary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  team: Array<{
    _id: string;
    name: string;
    role: string;
    initials: string | null;
    photo: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
    bio: string | null;
    funFact: {
      label?: string;
      text?: string;
    } | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: FAQ_PAGE_QUERY
// Query: *[_type == "faqPage"][0]{    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },    ctaHeadline,    ctaBody,    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} },    "groups": *[_type == "faqGroup"] | order(order asc, title asc) {      _id,      title,      navLabel,      "slug": slug.current,      items[] { question, answer }    }  }
export type FAQ_PAGE_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: Headline;
    intro: RichText | null;
    cta: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    sticker: string | null;
  } | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButtons: {
    primary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    secondary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  groups: Array<{
    _id: string;
    title: string;
    navLabel: string;
    slug: string;
    items: Array<{
      question: string;
      answer: RichText;
    }>;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: FREE_AUDIT_PAGE_QUERY
// Query: *[_type == "freeAuditPage"][0]{    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },    navCtaLabel,    coverHeader { eyebrow, headline, sticker, intro },    coverCards[] { title, description, tag },    forYouHeader { eyebrow, headline, sticker, intro },    forYouPointers,    deliverablesHeader { eyebrow, headline, sticker, intro },    deliverables[] { title, description, tag },    faqHeader { eyebrow, headline, sticker, intro },    faqItems[] { question, answer },    proofHeader { eyebrow, headline, sticker, intro },    proofSticker,    proofBody,    ctaHeadline,    ctaBody,    ctaButton { label, href, openInNewTab },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type FREE_AUDIT_PAGE_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: Headline;
    intro: RichText | null;
    cta: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    sticker: string | null;
  } | null;
  navCtaLabel: string | null;
  coverHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  coverCards: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  forYouHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  forYouPointers: Array<string> | null;
  deliverablesHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  deliverables: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  faqHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  faqItems: Array<{
    question: string;
    answer: RichText;
  }> | null;
  proofHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  proofSticker: string | null;
  proofBody: string | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButton: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: NEWSLETTER_PAGE_QUERY
// Query: *[_type == "newsletterPage"][0]{    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },    formTitle,    formButtonLabel,    formDisclaimer,    formSuccessSticker,    formSuccessText,    whyHeader { eyebrow, headline, sticker, intro },    whyReasons[] { title, description, tag },    insideHeader { eyebrow, headline, sticker, intro },    insideItems[] { title, description, tag },    afterHoursHeader { eyebrow, headline, sticker, intro },    afterHoursBody,    ctaEyebrow,    ctaHeadline,    ctaBody,    ctaButton { label, href, openInNewTab },    ctaSecondaryLabel,    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type NEWSLETTER_PAGE_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: Headline;
    intro: RichText | null;
    cta: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    sticker: string | null;
  } | null;
  formTitle: string | null;
  formButtonLabel: string | null;
  formDisclaimer: string | null;
  formSuccessSticker: string | null;
  formSuccessText: string | null;
  whyHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  whyReasons: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  insideHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  insideItems: Array<{
    title: string;
    description: string;
    tag: string | null;
  }> | null;
  afterHoursHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  afterHoursBody: RichText | null;
  ctaEyebrow: string | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButton: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  ctaSecondaryLabel: string | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: BLOG_INDEX_QUERY
// Query: *[_type == "blogIndexPage"][0]{    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },    topReadsHeader { eyebrow, headline, sticker, intro },    archiveHeader { eyebrow, headline, sticker, intro },    newsletterHeadline,    newsletterBody,    newsletterCta { label, href, openInNewTab },    ctaHeadline,    ctaBody,    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} },    "topReads": *[_type == "post" && featured == true && defined(slug.current)]      | order(publishedAt desc)[0...3] {  _id,  title,  "slug": slug.current,  dek,  publishedAt,  "readTime": coalesce(    readTime,    math::max([1, round(length(pt::text(body)) / 5 / 220)])  ),  heroImage {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  category-> { _id, title, "slug": slug.current }},    "posts": *[_type == "post" && defined(slug.current)]      | order(publishedAt desc) {  _id,  title,  "slug": slug.current,  dek,  publishedAt,  "readTime": coalesce(    readTime,    math::max([1, round(length(pt::text(body)) / 5 / 220)])  ),  heroImage {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  category-> { _id, title, "slug": slug.current }},    "categories": *[_type == "category"] | order(order asc, title asc) { _id, title, "slug": slug.current }  }
export type BLOG_INDEX_QUERY_RESULT = {
  hero: {
    badge: string | null;
    headline: Headline;
    intro: RichText | null;
    cta: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    sticker: string | null;
  } | null;
  topReadsHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  archiveHeader: {
    eyebrow: string | null;
    headline: Headline | null;
    sticker: string | null;
    intro: RichText | null;
  } | null;
  newsletterHeadline: Headline | null;
  newsletterBody: RichText | null;
  newsletterCta: {
    label: string;
    href: string;
    openInNewTab: boolean | null;
  } | null;
  ctaHeadline: Headline | null;
  ctaBody: RichText | null;
  ctaButtons: {
    primary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
    secondary: {
      label: string;
      href: string;
      openInNewTab: boolean | null;
    } | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  topReads: Array<{
    _id: string;
    title: string;
    slug: string;
    dek: string;
    publishedAt: string;
    readTime: number | 1;
    heroImage: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
  }>;
  posts: Array<{
    _id: string;
    title: string;
    slug: string;
    dek: string;
    publishedAt: string;
    readTime: number | 1;
    heroImage: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
  }>;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    dek,    publishedAt,    "readTime": coalesce(      readTime,      math::max([1, round(length(pt::text(body)) / 5 / 220)])    ),    heroImage {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},    category-> { _id, title, "slug": slug.current },    author-> {  _id,  name,  role,  initials,  photo {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  bio,  funFact},    body[]{      ...,      _type == "figure" => { ..., "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }    },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} },    "related": select(      count(related) > 0 => related[]-> {  _id,  title,  "slug": slug.current,  dek,  publishedAt,  "readTime": coalesce(    readTime,    math::max([1, round(length(pt::text(body)) / 5 / 220)])  ),  heroImage {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  category-> { _id, title, "slug": slug.current }},      *[_type == "post" && slug.current != $slug && category._ref == ^.category._ref]        | order(publishedAt desc)[0...3] {  _id,  title,  "slug": slug.current,  dek,  publishedAt,  "readTime": coalesce(    readTime,    math::max([1, round(length(pt::text(body)) / 5 / 220)])  ),  heroImage {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions},  category-> { _id, title, "slug": slug.current }}    )  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  dek: string;
  publishedAt: string;
  readTime: number | 1;
  heroImage: {
    _type: "figure";
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  author: {
    _id: string;
    name: string;
    role: string;
    initials: string | null;
    photo: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
    bio: string | null;
    funFact: {
      label?: string;
      text?: string;
    } | null;
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        text: string;
        _type: "callout";
        _key: string;
      }
    | {
        _key: string;
        _type: "figure";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      }
    | {
        text: string;
        attribution?: string;
        _type: "pullQuote";
        _key: string;
      }
  > | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
  related: Array<{
    _id: string;
    title: string;
    slug: string;
    dek: string;
    publishedAt: string;
    readTime: number | 1;
    heroImage: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: SERVICE_SLUGS_QUERY
// Query: *[_type == "servicePage" && defined(slug.current)]{ "slug": slug.current }
export type SERVICE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: SERVICE_PAGE_QUERY
// Query: *[_type == "servicePage" && slug.current == $slug][0]{    _id,    category,    "slug": slug.current,    heroHeadline,    heroSub,    problemHeadline,    problemBody,    offerings[] { title, description, tag },    differently,    testimonial,    faq[] { question, answer },    quoteHeadline,    serviceScope,    serviceCheckboxes,    talkHeadline,    talkBody,    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type SERVICE_PAGE_QUERY_RESULT = {
  _id: string;
  category: string;
  slug: string;
  heroHeadline: Headline;
  heroSub: string;
  problemHeadline: string;
  problemBody: RichText | null;
  offerings: Array<{
    title: string;
    description: string;
    tag: string | null;
  }>;
  differently: Array<string> | null;
  testimonial: string | null;
  faq: Array<{
    question: string;
    answer: RichText;
  }> | null;
  quoteHeadline: string;
  serviceScope: string | null;
  serviceCheckboxes: Array<string> | null;
  talkHeadline: string | null;
  talkBody: string | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LEGAL_SLUGS_QUERY
// Query: *[_type == "legalDoc" && defined(slug.current)] | order(order asc){ "slug": slug.current }
export type LEGAL_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: LEGAL_DOC_QUERY
// Query: *[_type == "legalDoc" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    label,    eyebrow,    entity,    updatedAt,    intro,    sections[]{      _key,      title,      blocks[]{ ... }    },    seo { title, description, noIndex, image {  ...,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions} }  }
export type LEGAL_DOC_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  label: string | null;
  eyebrow: string | null;
  entity: string | null;
  updatedAt: string;
  intro: string;
  sections: Array<{
    _key: string;
    title: string;
    blocks: Array<
      | {
          _key: string;
          _type: "legalClause";
          number: string;
          heading: string;
          text: string;
        }
      | {
          _key: string;
          _type: "legalContact";
          name: string;
          city?: string;
          email: string;
        }
      | {
          _key: string;
          _type: "legalDefinition";
          term: string;
          text: string;
        }
      | {
          _key: string;
          _type: "legalList";
          items: Array<string>;
        }
      | {
          _key: string;
          _type: "legalNote";
          text: string;
        }
      | {
          _key: string;
          _type: "legalParagraph";
          text: string;
        }
      | {
          _key: string;
          _type: "legalSubheading";
          number: string;
          heading: string;
        }
    >;
  }>;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      _type: "figure";
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0]{\n    title,\n    tagline,\n    contactEmail,\n    marqueeText,\n    headerNav[] { label, href, openInNewTab },\n    headerCta { label, href, openInNewTab },\n    footerGroups[] {\n      title,\n      links[] { label, href, openInNewTab }\n    },\n    footerNote,\n    socialLinks[] { label, href, openInNewTab },\n    defaultSeo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage"][0]{\n    heroBadge,\n    heroHeadline,\n    heroIntro,\n    heroCta { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },\n    heroFootnote,\n    heroStickerA,\n    heroStickerB,\n\n    problemHeader { eyebrow, headline, sticker, intro },\n    problemBody,\n    lookalikes,\n    problemSticker,\n    problemCaption,\n\n    funnelHeader { eyebrow, headline, sticker, intro },\n    funnelStages[] {\n      title,\n      tag,\n      description,\n      bullets,\n      barWidth,\n      "href": servicePage->slug.current\n    },\n    funnelOutcomeSticker,\n    funnelOutcomeText,\n\n    whyHeader { eyebrow, headline, sticker, intro },\n    whyReasons[] { title, description, tag },\n\n    howHeader { eyebrow, headline, sticker, intro },\n    howPhases[] { title, description, tag },\n    howBanner,\n\n    whoHeader { eyebrow, headline, sticker, intro },\n    whoSegments[] { title, description, tag },\n\n    proofHeader { eyebrow, headline, sticker, intro },\n    proofBody,\n    proofCta { label, href, openInNewTab },\n    proofSticker,\n\n    auditHeader { eyebrow, headline, sticker, intro },\n    auditBody,\n    auditCta { label, href, openInNewTab },\n    auditSticker,\n    auditListTitle,\n    auditItems,\n\n    faqHeader { eyebrow, headline, sticker, intro },\n    faqItems[] { question, answer },\n\n    ctaHeadline,\n    ctaBody,\n    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },\n\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': HOME_PAGE_QUERY_RESULT;
    '\n  *[_type == "aboutPage"][0]{\n    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },\n    whatWeAreEyebrow,\n    whatWeAreBody,\n    missionEyebrow,\n    missionStatement,\n    storyEyebrow,\n    storyHeadline,\n    storyBeats,\n    teamEyebrow,\n    teamHeadline,\n    teamSticker,\n    teamIntro,\n    ctaEyebrow,\n    ctaHeadline,\n    ctaBody,\n    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} },\n    "team": *[_type == "person" && onTeamPage == true] | order(order asc, name asc) {\n  _id,\n  name,\n  role,\n  initials,\n  photo {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  bio,\n  funFact\n}\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_type == "faqPage"][0]{\n    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },\n    ctaHeadline,\n    ctaBody,\n    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} },\n    "groups": *[_type == "faqGroup"] | order(order asc, title asc) {\n      _id,\n      title,\n      navLabel,\n      "slug": slug.current,\n      items[] { question, answer }\n    }\n  }\n': FAQ_PAGE_QUERY_RESULT;
    '\n  *[_type == "freeAuditPage"][0]{\n    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },\n    navCtaLabel,\n    coverHeader { eyebrow, headline, sticker, intro },\n    coverCards[] { title, description, tag },\n    forYouHeader { eyebrow, headline, sticker, intro },\n    forYouPointers,\n    deliverablesHeader { eyebrow, headline, sticker, intro },\n    deliverables[] { title, description, tag },\n    faqHeader { eyebrow, headline, sticker, intro },\n    faqItems[] { question, answer },\n    proofHeader { eyebrow, headline, sticker, intro },\n    proofSticker,\n    proofBody,\n    ctaHeadline,\n    ctaBody,\n    ctaButton { label, href, openInNewTab },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': FREE_AUDIT_PAGE_QUERY_RESULT;
    '\n  *[_type == "newsletterPage"][0]{\n    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },\n    formTitle,\n    formButtonLabel,\n    formDisclaimer,\n    formSuccessSticker,\n    formSuccessText,\n    whyHeader { eyebrow, headline, sticker, intro },\n    whyReasons[] { title, description, tag },\n    insideHeader { eyebrow, headline, sticker, intro },\n    insideItems[] { title, description, tag },\n    afterHoursHeader { eyebrow, headline, sticker, intro },\n    afterHoursBody,\n    ctaEyebrow,\n    ctaHeadline,\n    ctaBody,\n    ctaButton { label, href, openInNewTab },\n    ctaSecondaryLabel,\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': NEWSLETTER_PAGE_QUERY_RESULT;
    '\n  *[_type == "blogIndexPage"][0]{\n    hero { badge, headline, intro, cta { label, href, openInNewTab }, sticker },\n    topReadsHeader { eyebrow, headline, sticker, intro },\n    archiveHeader { eyebrow, headline, sticker, intro },\n    newsletterHeadline,\n    newsletterBody,\n    newsletterCta { label, href, openInNewTab },\n    ctaHeadline,\n    ctaBody,\n    ctaButtons { primary { label, href, openInNewTab }, secondary { label, href, openInNewTab } },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} },\n    "topReads": *[_type == "post" && featured == true && defined(slug.current)]\n      | order(publishedAt desc)[0...3] {\n  _id,\n  title,\n  "slug": slug.current,\n  dek,\n  publishedAt,\n  "readTime": coalesce(\n    readTime,\n    math::max([1, round(length(pt::text(body)) / 5 / 220)])\n  ),\n  heroImage {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  category-> { _id, title, "slug": slug.current }\n},\n    "posts": *[_type == "post" && defined(slug.current)]\n      | order(publishedAt desc) {\n  _id,\n  title,\n  "slug": slug.current,\n  dek,\n  publishedAt,\n  "readTime": coalesce(\n    readTime,\n    math::max([1, round(length(pt::text(body)) / 5 / 220)])\n  ),\n  heroImage {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  category-> { _id, title, "slug": slug.current }\n},\n    "categories": *[_type == "category"] | order(order asc, title asc) { _id, title, "slug": slug.current }\n  }\n': BLOG_INDEX_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    dek,\n    publishedAt,\n    "readTime": coalesce(\n      readTime,\n      math::max([1, round(length(pt::text(body)) / 5 / 220)])\n    ),\n    heroImage {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n    category-> { _id, title, "slug": slug.current },\n    author-> {\n  _id,\n  name,\n  role,\n  initials,\n  photo {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  bio,\n  funFact\n},\n    body[]{\n      ...,\n      _type == "figure" => { ..., "lqip": asset->metadata.lqip, "dimensions": asset->metadata.dimensions }\n    },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} },\n    "related": select(\n      count(related) > 0 => related[]-> {\n  _id,\n  title,\n  "slug": slug.current,\n  dek,\n  publishedAt,\n  "readTime": coalesce(\n    readTime,\n    math::max([1, round(length(pt::text(body)) / 5 / 220)])\n  ),\n  heroImage {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  category-> { _id, title, "slug": slug.current }\n},\n      *[_type == "post" && slug.current != $slug && category._ref == ^.category._ref]\n        | order(publishedAt desc)[0...3] {\n  _id,\n  title,\n  "slug": slug.current,\n  dek,\n  publishedAt,\n  "readTime": coalesce(\n    readTime,\n    math::max([1, round(length(pt::text(body)) / 5 / 220)])\n  ),\n  heroImage {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n},\n  category-> { _id, title, "slug": slug.current }\n}\n    )\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "servicePage" && defined(slug.current)]{ "slug": slug.current }\n': SERVICE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "servicePage" && slug.current == $slug][0]{\n    _id,\n    category,\n    "slug": slug.current,\n    heroHeadline,\n    heroSub,\n    problemHeadline,\n    problemBody,\n    offerings[] { title, description, tag },\n    differently,\n    testimonial,\n    faq[] { question, answer },\n    quoteHeadline,\n    serviceScope,\n    serviceCheckboxes,\n    talkHeadline,\n    talkBody,\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': SERVICE_PAGE_QUERY_RESULT;
    '\n  *[_type == "legalDoc" && defined(slug.current)] | order(order asc){ "slug": slug.current }\n': LEGAL_SLUGS_QUERY_RESULT;
    '\n  *[_type == "legalDoc" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    label,\n    eyebrow,\n    entity,\n    updatedAt,\n    intro,\n    sections[]{\n      _key,\n      title,\n      blocks[]{ ... }\n    },\n    seo { title, description, noIndex, image {\n  ...,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n} }\n  }\n': LEGAL_DOC_QUERY_RESULT;
  }
}
